# Generated by Django 4.1.2 on 2022-11-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_address_profile_birth_certificate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='photo',
        ),
    ]
