# Generated by Django 4.1.2 on 2022-11-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_avatar_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='avatar',
        ),
    ]
