# Generated by Django 4.1.2 on 2022-12-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_photo_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
