# Generated by Django 4.1.2 on 2022-12-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
