# Generated by Django 4.1.2 on 2023-01-31 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_varified',
        ),
    ]
