# Generated by Django 4.1.4 on 2022-12-23 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BkashPayment',
        ),
    ]
