# Generated by Django 4.1.2 on 2022-12-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkash', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkashpay',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bkashpay',
            name='phone',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='bkashpay',
            name='pin',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
