# Generated by Django 4.1.2 on 2022-11-22 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality_name', models.CharField(max_length=100)),
                ('post_code', models.IntegerField(blank=True, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingApp.division')),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garage_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('photo', models.ImageField(blank=True, upload_to='garage_photos')),
                ('location', models.CharField(max_length=100)),
                ('place_category', models.CharField(choices=[('Commercial', 'Commercial'), ('Residential', 'Residential')], default='Commercial', max_length=20)),
                ('bike_slot', models.IntegerField()),
                ('car_slot', models.IntegerField()),
                ('bicycle_slot', models.IntegerField()),
                ('allow_monthly', models.BooleanField(default=True)),
                ('monthly_cost', models.FloatField()),
                ('allow_hourly', models.BooleanField(default=True)),
                ('hourly_cost', models.FloatField()),
                ('opening_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('facility', models.CharField(choices=[('CCTV', 'CCTV'), ('Gaurd', 'Gaurd'), ('Indoor', 'Indoor')], default='CCTV', max_length=20)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingApp.locality')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('vehice_number_plate', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(choices=[('Bike', 'Bike'), ('Car', 'Car'), ('Bicycle', 'Bicycle')], default='Car', max_length=20)),
                ('documentation', models.ImageField(blank=True, null=True, upload_to='Booking_document')),
                ('status', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingApp.garage')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingApp.locality')),
            ],
        ),
    ]
