# Generated by Django 4.1.2 on 2022-11-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='facility',
        ),
        migrations.AddField(
            model_name='garage',
            name='CCTV',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='garage',
            name='Gaurd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='garage',
            name='Indoor',
            field=models.BooleanField(default=False),
        ),
    ]
