# Generated by Django 4.1.2 on 2022-11-23 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0002_remove_garage_facility_garage_cctv_garage_gaurd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='owner',
        ),
        migrations.AddField(
            model_name='garage',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parkingApp.division'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='garage',
            name='photo',
            field=models.ImageField(upload_to='garage_photos'),
        ),
    ]
