# Generated by Django 4.1.2 on 2022-11-24 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0003_remove_garage_owner_garage_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='bicycle_slot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='garage',
            name='bike_slot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='garage',
            name='car_slot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='garage',
            name='description',
            field=models.CharField(default='No description', max_length=500),
        ),
        migrations.AlterField(
            model_name='garage',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage', to='parkingApp.division'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage', to='parkingApp.locality'),
        ),
    ]
