# Generated by Django 4.1.2 on 2022-11-24 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0004_alter_garage_bicycle_slot_alter_garage_bike_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='division',
        ),
    ]
