# Generated by Django 4.1.2 on 2022-11-26 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parkingApp', '0008_alter_garage_cctv_alter_garage_gaurd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL),
        ),
    ]
