# Generated by Django 4.1.2 on 2022-12-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0011_garage_lat_garage_lng'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='location',
            new_name='Owner_address',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='vehice_number_plate',
            new_name='vehice_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
