# Generated by Django 4.1.2 on 2022-12-02 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0016_alter_booking_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='location',
        ),
    ]
