# Generated by Django 4.1.2 on 2022-12-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0021_remove_booking_other_number_garage_other_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Owner_address',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='documentation',
            new_name='image_of_necesssary_papers',
        ),
        migrations.AddField(
            model_name='booking',
            name='type_of_booking',
            field=models.CharField(choices=[('Hour', 'Hour'), ('Day', 'Day'), ('Month', 'Month')], default='Hour', max_length=20),
        ),
    ]
