# Generated by Django 4.1.2 on 2022-12-02 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0022_rename_owner_address_booking_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
