# Generated by Django 4.1.2 on 2022-12-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0024_remove_garage_allow_hourly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='allow_hourly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='garage',
            name='allow_monthly',
            field=models.BooleanField(default=True),
        ),
    ]
