# Generated by Django 4.1.2 on 2022-12-06 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0025_garage_allow_hourly_garage_allow_monthly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='book',
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garage',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
