# Generated by Django 4.1.2 on 2022-12-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0026_remove_garage_book_booking_time_garage_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='garage',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='garage',
            name='allow_daily',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='garage',
            name='daily_cost',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
    ]
