# Generated by Django 4.1.2 on 2022-12-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0030_alter_garage_daily_cost_alter_garage_hourly_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
