# Generated by Django 4.1.2 on 2022-12-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0031_booking_booking_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='customer_review',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
