# Generated by Django 4.1.2 on 2022-12-14 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parkingApp', '0032_garage_customer_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='customer_review',
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(blank=True, max_length=500, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_customer', to=settings.AUTH_USER_MODEL)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='parkingApp.garage')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
