# Generated by Django 4.1.2 on 2022-12-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0033_remove_garage_customer_review_customerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='garage',
            name='ratingCount',
            field=models.IntegerField(default=0),
        ),
    ]
