# Generated by Django 4.1.2 on 2022-12-16 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0034_garage_rating_garage_ratingcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreview',
            name='rating',
        ),
    ]
