# Generated by Django 4.1.2 on 2022-12-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0035_remove_customerreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
