# Generated by Django 4.1.2 on 2022-12-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0036_alter_garage_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='garage',
            name='ratingCount',
            field=models.FloatField(default=0),
        ),
    ]
