# Generated by Django 4.1.2 on 2022-12-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0037_alter_garage_rating_alter_garage_ratingcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='garage',
            name='ratingCount',
            field=models.IntegerField(default=0),
        ),
    ]
