# Generated by Django 4.1.2 on 2022-12-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0038_alter_garage_rating_alter_garage_ratingcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='avgRating',
            field=models.FloatField(default=0),
        ),
    ]
