# Generated by Django 4.1.2 on 2022-12-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0039_garage_avgrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='totalAmount',
            field=models.FloatField(default=0),
        ),
    ]
