# Generated by Django 4.1.2 on 2023-01-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0042_garage_postalcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postalcode',
            name='neighbouring_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
