# Generated by Django 4.1.2 on 2023-01-22 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0043_alter_postalcode_neighbouring_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locality',
            name='post_code',
        ),
    ]
