# Generated by Django 4.1.2 on 2023-01-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0044_remove_locality_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='post_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
