# Generated by Django 4.1.2 on 2023-01-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0045_locality_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='postalCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
